### ISSUE TITLE
Feature request: callback on upload start

### ISSUE THREAD

**Issue by Pikokosan** [vovagorodok/ArduinoBleOTA#12]
I'd like to see a call back function to know when the update is started and finished. The project i've been implementing this into has a serial based screen. id like to be able to call up the updating screen when the device is updating and call back to the normal screen when complete.

**Comment by vovagorodok** [comment]
Done: https://github.com/vovagorodok/ArduinoBleOTA/commit/2dffff95e794252d4b46298ea7b8d13fe26f209f

**Comment by vovagorodok** [comment]
I'll close it. Fill free to reopen
