### ISSUE TITLE
Where do all the includes in BleOtaStorage.h come from ? 

### ISSUE THREAD

**Issue by sdetweil** [vovagorodok/ArduinoBleOTA#13]
I don't see an InternalStorageESP.h, just trying to build using examples/basic/main.ino

```
In file included from /Users/sam/Documents/Arduino/libraries/ArduinoBleOTA-main/src/ArduinoBleOtaClass.h:2,
                 from /Users/sam/Documents/Arduino/libraries/ArduinoBleOTA-main/src/ArduinoBleOTA.h:6,
                 from /Users/sam/Documents/Arduino/test_ota/test_ota.ino:1:
/Users/sam/Documents/Arduino/libraries/ArduinoBleOTA-main/src/BleOtaStorage.h:13:10: fatal error: InternalStorageESP.h: No such file or directory
 #include "InternalStorageESP.h"
          ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vovagorodok** [comment]
It's from `jandrassy/ArduinoOTA@^1.0.9`, that ArduinoBleOTA depends on

See:
https://github.com/vovagorodok/ArduinoBleOTA/blob/main/platformio.ini

**Comment by sdetweil** [comment]
yeh, not using platformio..

**Comment by vovagorodok** [comment]
What are you using? And what I should add in library in order to see dependencies by users?

**Comment by sdetweil** [comment]
I am using Arduino IDE

so I had to download each lib as a zip and add as library..

I am trying to add ESP32 non nimble to your lib, as I can't get Nimble to work  and a couple other things..

I have already created a BLE server, so I don't need you to do that
and I control advertising, not you.. 

so I need another begin()  method where I pass the server and advise on advertising...
and it should return the service pointer.

**Comment by sdetweil** [comment]
so a comment in the doc with the github links to  dependencies if not using platformio

**Comment by sdetweil** [comment]
using platfrormio now
