### ISSUE TITLE
Publish library in platformio

### ISSUE THREAD

**Issue by sdetweil** [vovagorodok/ArduinoBleOTA#14]
Error: Could not find the package with 'vovagorodok/ArduinoBleOTA' requirements for your system 'darwin_arm64'
my platform.ini def 
```
[env:esp32doit-devkit-v1-ota]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	arduino-libraries/Arduino_JSON@^0.2.0
	adafruit/Adafruit VL53L1X@^3.1.0
        vovagorodok/ArduinoBleOTA
```

other libs worked ok..

**Comment by vovagorodok** [comment]
It still under development and ArduinoBleOta is not published in platformio yet.
I'll publish it after all tests.
Currently you can add full path:
```
https://github.com/vovagorodok/ArduinoBleOTA
```
instead of:
```
vovagorodok/ArduinoBleOTA
```
And remove full path when I publish ArduinoBleOTA in platformio

**Comment by vovagorodok** [comment]
Remember to add dependencies:
```
jandrassy/ArduinoOTA@^1.0.9
bakercp/CRC32@^2.0.0
h2zero/NimBLE-Arduino@^1.4.1
rlogiacco/CircularBuffer@^1.3.3
```

**Comment by sdetweil** [comment]
yes, added, shame platformio doesn't do recursive deps.. anyhow.. now have a build failure in the ArduinoOTA package..

**Comment by vovagorodok** [comment]
> platformio doesn't do recursive deps..

should do by default after adding [library.json](https://github.com/vovagorodok/ArduinoBleOTA/pull/11/files#diff-64cc7cdde6789dc1c1c4a6f406cd1ff6a6a00027097788e2d52fc27b0d75502e)
Will be added soon in https://github.com/vovagorodok/ArduinoBleOTA/pull/11
(if not please add `lib_ldf_mode = deep+` in platformio.ini)

> build failure in the ArduinoOTA package..

Please show error

**Comment by sdetweil** [comment]
thx, fixed that
