### ISSUE TITLE
dbus Module not found while using `uploader.py`

### ISSUE THREAD

**Issue by HareshPrajapati** [vovagorodok/ArduinoBleOTA#22]
With Windows 10 and the script available in /tools/uploader.py, I am attempting to do OTA, but I am receiving a module not found error in python script (see image).
The "dbus-python" module would not install; it appears to be out of date.
please help..!!
![image](https://imgur.com/0sK1sBr.png)

**Comment by vovagorodok** [comment]
Hi, dbus is linux-only module. I have plans to create script for other os: https://github.com/vovagorodok/ArduinoBleOTA/issues/18

**Comment by HareshPrajapati** [comment]
Okay, Thanks !
If possible then use [Bleak](https://github.com/hbldh/bleak).

**Comment by vovagorodok** [comment]
Done. Please check
