### ISSUE TITLE
which crc lib?

### ISSUE THREAD

**Issue by sdetweil** [vovagorodok/ArduinoBleOTA#27]
I am looking for a working crc for nodejs app.

the one I have produces different results with running crc like python code and one time like flutter app.
and different than bleota code version

**Comment by vovagorodok** [comment]
BleOta uses default CRC32 calculation. Find nodejs library with that

**Comment by sdetweil** [comment]
thanks. first two produce different results...

**Comment by vovagorodok** [comment]
Hmm, am I understand correctly uploader.sh and flutter app has different crc result for same binary?

**Comment by sdetweil** [comment]
>correctly uploader.sh and flutter app has different crc result for same binary
no, you just use two different approaches,   flutter is from one buffer, uploader is incremental 

man this is harder than it should be

download the same file from the same server, wrote a node test app 

same crc as your lib
your lib gets the data from my app (so that is good) 
my app calculates from full data (like you flutter app)  like the node test app 

node test app 226795867 
your lib 226795867 

my app BEFORE sending the data 3074055154, technically the crc lib returns signed number -1220912142 


finally had to embed in source 
https://stackoverflow.com/questions/18638900/javascript-crc32

**Comment by sdetweil** [comment]
working
